0: thread affinity: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63}
0: Collecting environment information...
0: PyTorch version: 2.3.0a0+40ec155e58.nv24.03
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.8.0-1013-nvidia-64k-aarch64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GH200 480GB
Nvidia driver version: 550.90.12
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.9.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv.so.9.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn.so.9.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_engines_precompiled.so.9.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_graph.so.9.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_heuristic.so.9.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops.so.9.0.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         aarch64
CPU op-mode(s):                       64-bit
Byte Order:                           Little Endian
CPU(s):                               64
On-line CPU(s) list:                  0-63
Vendor ID:                            ARM
Model:                                0
Thread(s) per core:                   1
Core(s) per cluster:                  64
Socket(s):                            -
Cluster(s):                           1
Stepping:                             r0p0
BogoMIPS:                             2000.00
Flags:                                fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint svei8mm svebf16 i8mm bf16 dgh bti
NUMA node(s):                         9
NUMA node0 CPU(s):                    0-63
NUMA node1 CPU(s):                    
NUMA node2 CPU(s):                    
NUMA node3 CPU(s):                    
NUMA node4 CPU(s):                    
NUMA node5 CPU(s):                    
NUMA node6 CPU(s):                    
NUMA node7 CPU(s):                    
NUMA node8 CPU(s):                    
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; __user pointer sanitization
Vulnerability Spectre v2:             Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.15.0rc2
[pip3] onnxruntime==1.19.2
[pip3] optree==0.10.0
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-transformers==1.1.0
[pip3] pytorch-triton==2.2.0+e28a256d7
[pip3] torch==2.3.0a0+40ec155e58.nv24.3
[pip3] torch-tensorrt==2.3.0a0
[pip3] torchdata==0.7.1a0
[pip3] torchtext==0.17.0a0
[pip3] torchvision==0.18.0a0
[conda] Could not collect
0: Saving results to: gnmt
0: Run arguments: Namespace(dataset_dir='/data/gnmt/wmt16_de_en', src_lang='en', tgt_lang='de', vocab='/data/gnmt/wmt16_de_en/vocab.bpe.32000', bpe_codes='/data/gnmt/wmt16_de_en/bpe.32000', train_src='/data/gnmt/wmt16_de_en/train.tok.clean.bpe.32000.en', train_tgt='/data/gnmt/wmt16_de_en/train.tok.clean.bpe.32000.de', val_src='/data/gnmt/wmt16_de_en/newstest_dev.tok.clean.bpe.32000.en', val_tgt='/data/gnmt/wmt16_de_en/newstest_dev.tok.clean.bpe.32000.de', test_src='/data/gnmt/wmt16_de_en/newstest2014.tok.bpe.32000.en', test_tgt='/data/gnmt/wmt16_de_en/newstest2014.de', save_dir='gnmt', print_freq=10, warmup=1, hidden_size=1024, num_layers=4, dropout=0.2, share_embedding=True, smoothing=0.1, math='fp32', seed=2, prealloc_mode='always', dllog_file='train_log.json', affinity='socket_unique_interleaved', eval=True, env=True, cuda=True, cudnn=True, log_all_ranks=True, train_max_size=None, train_batch_size=1152, train_global_batch_size=None, train_iter_size=1, epochs=2, grad_clip=5.0, train_max_length=50, train_min_length=0, train_loader_workers=64, batching='bucketing', shard_size=80, num_buckets=5, optimizer='Adam', lr=0.002, optimizer_extra='{}', init_scale=8192, upscale_interval=128, warmup_steps=200, remain_steps=0.666, decay_interval=None, decay_steps=4, decay_factor=0.5, val_batch_size=64, val_max_length=125, val_min_length=0, val_loader_workers=0, test_batch_size=128, test_max_length=150, test_min_length=0, beam_size=5, len_norm_factor=0.6, cov_penalty_factor=0.1, len_norm_const=5.0, intra_epoch_eval=0, test_loader_workers=0, start_epoch=0, resume=None, save_all=False, save_freq=5000, keep_checkpoints=0, target_perf=None, target_bleu=None, local_rank=0, lang={'src': 'en', 'tgt': 'de'}, rank=0)
0: Using master seed from command line: 2
0: Worker 0 is using worker seed: 242886303
Traceback (most recent call last):
  File "/workspace/benchmark/Translation/GNMT/train.py", line 659, in <module>
    main()
  File "/workspace/benchmark/Translation/GNMT/train.py", line 427, in main
    tokenizer = Tokenizer(args.vocab, args.bpe_codes, args.lang, pad_vocab)
  File "/workspace/benchmark/Translation/GNMT/seq2seq/data/tokenizer.py", line 50, in __init__
    with open(bpe_fname, 'r') as bpe_codes:
FileNotFoundError: [Errno 2] No such file or directory: '/data/gnmt/wmt16_de_en/bpe.32000'
[2024-11-01 00:18:08,434] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 5571) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 834, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 825, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 137, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 271, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-01_00:18:08
  host      : 1c464adf3711
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 5571)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
DONE!
