DLL 2024-11-01 00:17:25.663168 - PARAMETER data : /data/ncf/cache/ml-20m  feature_spec_file : feature_spec.yaml  epochs : 2  batch_size : 8000000  valid_batch_size : 1048576  factors : 64  layers : [256, 256, 128, 64]  negative_samples : 4  learning_rate : 0.0045  topk : 10  seed : None  threshold : 1.0  beta1 : 0.25  beta2 : 0.5  eps : 1e-08  dropout : 0.5  checkpoint_dir :   load_checkpoint_path : None  mode : train  grads_accumulated : 1  amp : False  log_path : log.json  world_size : 1  distributed : False  local_rank : 0 
Traceback (most recent call last):
  File "/workspace/benchmark/Recommendation/NCF/ncf.py", line 383, in <module>
    main()
  File "/workspace/benchmark/Recommendation/NCF/ncf.py", line 224, in main
    feature_spec = FeatureSpec.from_yaml(feature_spec_path)
  File "/workspace/benchmark/Recommendation/NCF/feature_spec.py", line 30, in from_yaml
    with open(path, 'r') as feature_spec_file:
FileNotFoundError: [Errno 2] No such file or directory: '/data/ncf/cache/ml-20m/feature_spec.yaml'
[1c464adf3711:3572 :0:3572] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x190000b1f73620)
==== backtrace (tid:   3572) ====
 0 0x000000000008dbf4 free()  ???:0
 1 0x000000000018d358 OPENSSL_LH_strhash()  ???:0
 2 0x000000000018de4c OPENSSL_LH_doall()  ???:0
 3 0x0000000000195bfc CRYPTO_new_ex_data()  ???:0
 4 0x000000000019abd8 CRYPTO_free_ex_data()  ???:0
 5 0x0000000000195edc OpenSSL_version()  ???:0
 6 0x000000000019e30c OPENSSL_cleanup()  ???:0
 7 0x000000000003cde8 secure_getenv()  ???:0
 8 0x000000000003cf0c exit()  ???:0
 9 0x0000000000027400 __libc_init_first()  ???:0
10 0x00000000000274cc __libc_start_main()  ???:0
11 0x00000000001da630 _start()  ???:0
=================================
[2024-11-01 00:17:29,738] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -11) local_rank: 0 (pid: 3572) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 834, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 825, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 137, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 271, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
ncf.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-01_00:17:29
  host      : 1c464adf3711
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 3572)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 3572
======================================================
DONE!
